// plugins/power-pages/skills/create-site/assets/react/src/components/Layout.tsx
import { type ReactNode } from 'react'
import { Link, useLocation } from 'react-router-dom'

export default function Layout({ children }: { children: ReactNode }) {
  const location = useLocation()

  return (
    <div className="app">
      <header className="header">
        <nav className="nav">
          <Link to="/" className="logo">__SITE_NAME__</Link>
          <div className="nav-links">
            <Link to="/" className={location.pathname === '/' ? 'active' : ''}>Home</Link>
            <Link to="/about" className={location.pathname === '/about' ? 'active' : ''}>About</Link>
          </div>
        </nav>
      </header>
      <main className="main">{children}</main>
      <footer className="footer">
        <p>&copy; {new Date().getFullYear()} __SITE_NAME__</p>
      </footer>
    </div>
  )
}

// plugins/power-pages/skills/create-site/assets/vue/src/components/Layout.vue
<template>
  <div class="app">
    <header class="header">
      <nav class="nav">
        <RouterLink to="/" class="logo">__SITE_NAME__</RouterLink>
        <div class="nav-links">
          <RouterLink to="/" :class="{ active: route.path === '/' }">Home</RouterLink>
          <RouterLink to="/about" :class="{ active: route.path === '/about' }">About</RouterLink>
        </div>
      </nav>
    </header>
    <main class="main">
      <slot />
    </main>
    <footer class="footer">
      <p>&copy; {{ year }} __SITE_NAME__</p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from 'vue-router'

const route = useRoute()
const year = new Date().getFullYear()
</script>
