// plugins/power-pages/skills/create-site/assets/vue/src/components/Layout.vue
<template>
  <div class="app">
    <header class="header">
      <nav class="nav">
        <RouterLink to="/" class="logo">__SITE_NAME__</RouterLink>
        <div class="nav-links">
          <RouterLink to="/" :class="{ active: route.path === '/' }">Home</RouterLink>
          <RouterLink to="/about" :class="{ active: route.path === '/about' }">About</RouterLink>
        </div>
      </nav>
    </header>
    <main class="main">
      <slot />
    </main>
    <footer class="footer">
      <p>&copy; {{ year }} __SITE_NAME__</p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from 'vue-router'

const route = useRoute()
const year = new Date().getFullYear()
</script>

// plugins/power-pages/skills/create-site/assets/angular/src/app/components/layout.component.ts
import { Component } from '@angular/core'
import { RouterLink, RouterLinkActive } from '@angular/router'

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  template: `
    <div class="app">
      <header class="header">
        <nav class="nav">
          <a routerLink="/" class="logo">__SITE_NAME__</a>
          <div class="nav-links">
            <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">Home</a>
            <a routerLink="/about" routerLinkActive="active">About</a>
          </div>
        </nav>
      </header>
      <main class="main">
        <ng-content />
      </main>
      <footer class="footer">
        <p>&copy; {{ year }} __SITE_NAME__</p>
      </footer>
    </div>
  `,
})
export class LayoutComponent {
  year = new Date().getFullYear()
}
